# This file was generated by GoReleaser. DO NOT EDIT.
cask "eidos" do
  version "0.9.1"

  on_macos do
    on_intel do
      sha256 "05aa59b04dab5ef9cd13f037ce33ef1c016945092130db4386f96d1eb9b6a892"
      url "https://github.com/signalbreak-labs/eidos/releases/download/v#{version}/eidos_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "db3ea1d8db02a4c6f1a3472d36fd0844aefd4f83f6a55df575fb15caa05180f1"
      url "https://github.com/signalbreak-labs/eidos/releases/download/v#{version}/eidos_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "608480ea1dd806001d0a370215ba70c71627793a05d21ea42ec0278609b89225"
      url "https://github.com/signalbreak-labs/eidos/releases/download/v#{version}/eidos_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "a8afa721d342c2da11cd0349fe531efb479b2ba409952657cc0ab6e3371c6c8b"
      url "https://github.com/signalbreak-labs/eidos/releases/download/v#{version}/eidos_#{version}_linux_arm64.tar.gz"
    end
  end

  name "eidos"
  desc "Generate Terraform providers from OpenAPI 2.0/3.0/3.1 specs"
  homepage "https://github.com/signalbreak-labs/eidos"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "eidos"

  # No zap stanza required

end
