# This file was generated by GoReleaser. DO NOT EDIT.
cask "eidos" do
  version "0.7.1"

  on_macos do
    on_intel do
      sha256 "1b1c101e58e96bb6a2646175fda73ab65ef8a1e728e0bc883f7b02b231777cee"
      url "https://github.com/signalbreak-labs/eidos/releases/download/v#{version}/eidos_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "3e2990dbb4e7033b08c8b45ca8e2279acba59a3314fee22cb8534ba1df5ef353"
      url "https://github.com/signalbreak-labs/eidos/releases/download/v#{version}/eidos_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "d6ec504277fcc0334b4d031327b8491887e43ff992f8f9af62e5799fd9bc75f8"
      url "https://github.com/signalbreak-labs/eidos/releases/download/v#{version}/eidos_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "4d339039874b50518e29bd00c6d9a1d4c31470baf761d81d487c0e6683530196"
      url "https://github.com/signalbreak-labs/eidos/releases/download/v#{version}/eidos_#{version}_linux_arm64.tar.gz"
    end
  end

  name "eidos"
  desc "Generate Terraform providers from OpenAPI 2.0/3.0/3.1 specs"
  homepage "https://github.com/signalbreak-labs/eidos"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "eidos"

  # No zap stanza required

end
