# This file was generated by GoReleaser. DO NOT EDIT.
cask "eidos" do
  version "0.7.4"

  on_macos do
    on_intel do
      sha256 "392f788921eca855f3383592fe5b71f87fa7948f1ef0df2f1b91ec11cbba381a"
      url "https://github.com/signalbreak-labs/eidos/releases/download/v#{version}/eidos_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "a93404dbf52747fb8f624345818a4f0f9e139a30929fdd1a1bbef16576e109ac"
      url "https://github.com/signalbreak-labs/eidos/releases/download/v#{version}/eidos_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "19680100ab17b35fec6b0fd8b7d8c36c50b266d4246cea897298f1af07bf82cb"
      url "https://github.com/signalbreak-labs/eidos/releases/download/v#{version}/eidos_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "efa7bf2ac21bc3e3f58979f945fad1170a7ff9b86c9eaa0f7b8268290c557560"
      url "https://github.com/signalbreak-labs/eidos/releases/download/v#{version}/eidos_#{version}_linux_arm64.tar.gz"
    end
  end

  name "eidos"
  desc "Generate Terraform providers from OpenAPI 2.0/3.0/3.1 specs"
  homepage "https://github.com/signalbreak-labs/eidos"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "eidos"

  # No zap stanza required

end
